import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopNavBar from '@/components/top-nav'
import { Stack,Container } from '@mui/material';
import { ContactEmergency } from '@mui/icons-material';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 


{
  return (
    <>
    <Stack>
      <TopNavBar />
      <Container sx={{width: 1200}}>
        {children}
      </Container>
    </Stack>
    </>
  )
}
